# Generated by Django 4.2.25 on 2025-12-11 02:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Index",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Indices",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("task_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("items_scraped", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("Technology", "Technology"),
                            ("Healthcare", "Healthcare"),
                            ("Energy", "Energy"),
                            ("Industrial", "Industrial"),
                            ("Financial", "Financial"),
                            ("Consumer", "Consumer"),
                            ("Utilities", "Utilities"),
                            ("Materials", "Materials"),
                            ("Real Estate", "Real Estate"),
                            ("Communication", "Communication"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="ReportCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sp500_analysis", "S&P 500 Analysis"),
                            ("news_report", "News Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=2)),
                ("content", models.JSONField()),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("report_type", "language")},
            },
        ),
        migrations.CreateModel(
            name="MarketNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=500)),
                (
                    "headline_es",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("summary_es", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
                ("source", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("market", "Market"),
                            ("economy", "Economy"),
                            ("fed", "Federal Reserve"),
                            ("earnings", "Earnings"),
                            ("sector", "Sector"),
                            ("other", "Other"),
                        ],
                        default="market",
                        max_length=50,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_stocks",
                    models.ManyToManyField(
                        blank=True, related_name="market_news", to="dashboard.stock"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Market News",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("source", models.CharField(default="yahoo_finance", max_length=50)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="dashboard.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["stock", "-timestamp"],
                        name="dashboard_s_stock_i_899ae7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=500)),
                (
                    "headline_es",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("summary_es", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
                ("source", models.CharField(max_length=100)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="dashboard.stock",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stock News",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["stock", "-published_at"],
                        name="dashboard_s_stock_i_3ff514_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="dashboard_s_created_917477_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("market_cap", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "pe_trailing",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "pe_forward",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "peg_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "debt_equity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "current_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "quick_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "interest_coverage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("cash", models.CharField(blank=True, max_length=20, null=True)),
                ("total_debt", models.CharField(blank=True, max_length=20, null=True)),
                ("net_cash", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "free_cash_flow",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "gross_margin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "operating_margin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "net_margin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("gf_score", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "altman_z_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "piotroski_score",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "price_target",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "analyst_rating",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("STRONG_BUY", "Strong Buy"),
                            ("BUY", "Buy"),
                            ("HOLD", "Hold"),
                            ("SELL", "Sell"),
                            ("STRONG_SELL", "Strong Sell"),
                            ("HIGH_RISK", "High Risk/Reward"),
                        ],
                        default="HOLD",
                        max_length=20,
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("BULLISH", "Bullish"),
                            ("NEUTRAL", "Neutral"),
                            ("BEARISH", "Bearish"),
                        ],
                        default="NEUTRAL",
                        max_length=20,
                    ),
                ),
                ("conclusion_en", models.TextField(blank=True, null=True)),
                ("conclusion_es", models.TextField(blank=True, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("sources", models.JSONField(default=list)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="dashboard.stock",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stock Analyses",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["stock", "-timestamp"],
                        name="dashboard_s_stock_i_98f936_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IndexPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "pe_forward",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("source", models.CharField(default="yahoo_finance", max_length=50)),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="dashboard.index",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["index", "-timestamp"],
                        name="dashboard_i_index_i_0eb7d4_idx",
                    )
                ],
            },
        ),
    ]
